# Project information
site_name: "doccano-client"
site_description: "A simple client wrapper for doccano API."
site_author: "Hiroki Nakayama"
site_url: "https://doccano.github.io/doccano-client/"
docs_dir: .

# Repository
repo_name: "doccano/doccano-client"
repo_url: "https://github.com/doccano/doccano-client"

# Copyright
copyright: "Copyright &copy; 2018 - 2019 Hiroki Nakayama"

theme:
  name: "material"
  palette:
    primary: "cyan"
    accent: "cyan"
  show_sidebar: true

extra:
  social:
    - icon: "fontawesome/brands/github"
      link: "https://github.com/Hironsan"
    - icon: "fontawesome/brands/twitter"
      link: "https://twitter.com/Hironsan13"

plugins:
  - same-dir
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
            show_signature: false
            show_source: false
            show_root_full_path: false
            heading_level: 3

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

# Page tree
nav:
  - Overview: index.md
  - Install: install.md
  - Usage: usage.md
  - CLI: cli.md
